[build]
  command = "unzip -o coelecanth_repo.zip && cd coelecanth && npm ci && npm run build"
  publish = "coelecanth/dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
